FROM alpine:3.20

RUN apk add --no-cache mc nano sudo git xfce4 xfce4-terminal faenza-icon-theme bash python3 tigervnc \
            zsh zoxide zellij btop bat wget eza fzf fzf-zsh-plugin zsh-autosuggestions zsh-completions \
            zsh-history-substring-search zsh-syntax-highlighting font-meslo-nerd \
            firefox cmake wget openssl build-base nodejs npm \
            pulseaudio xfce4-pulseaudio-plugin pavucontrol pulseaudio-alsa alsa-plugins-pulse alsa-lib-dev \
    && adduser -h /home/alpine -s /bin/bash -S -D alpine && echo -e "alpine\nalpine" | passwd alpine \
    && echo 'alpine ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
    && git clone --depth=1 https://github.com/novnc/noVNC /opt/noVNC \
    && git clone --depth=1 https://github.com/novnc/websockify /opt/noVNC/utils/websockify

COPY scripts/audify.js /opt/noVNC/audify.js
COPY scripts/index.html /opt/noVNC/index.html
COPY scripts/pcm-player.js /opt/noVNC/pcm-player.js
COPY scripts/script.js /opt/noVNC/script.js

RUN npm install --prefix /opt/noVNC ws
RUN npm install --prefix /opt/noVNC audify
