services:
    mssqlserver:
        image: mcr.microsoft.com/azure-sql-edge
        container_name: mssqlserver
        restart: unless-stopped
        ports:
            - 1433:1433
        env_file:
            - stack.env
